package com.romullogirardi.wisconsin.view;

import java.util.Calendar;

import com.romullogirardi.wisconsin.model.Constants;
import com.romullogirardi.wisconsin.model.Manager;
import com.romullogirardi.wisconsin.model.Movement;
import com.romullogirardi.wisconsin.model.Enums.Strategy;
import com.romullogirardi.wisconsin.utils.PDFGenerator;

public class MainTest {

	public static void main(String[] args) {
	
		//Setting user name and initial time
		Manager.getInstance().setUserName("Rômullo Girardi Moreira");
		Manager.getInstance().setUserAge(30);
		Manager.getInstance().setInitialTime(Calendar.getInstance());
		
		//Setting movements
		Movement movement1 = new Movement(1, Strategy.COLOR, null, 0, false, false, true, false, false, false, null, false, false);
		Movement movement2 = new Movement(1, Strategy.COLOR, movement1, 1, true, true, false, false, false, false, null, false, false);
		Movement movement3 = new Movement(1, Strategy.COLOR, movement2, 2, true, true, false, false, false, false, null, false, false);
		Movement movement4 = new Movement(1, Strategy.COLOR, movement3, 3, true, true, false, false, false, false, null, false, false);
		Movement movement5 = new Movement(1, Strategy.COLOR, movement4, 4, true, true, false, false, false, false, null, false, false);
		Movement movement6 = new Movement(1, Strategy.COLOR, movement5, 0, false, false, true, false, false, false, null, false, false);
		Movement movement7 = new Movement(1, Strategy.COLOR, movement6, 1, true, true, false, false, false, false, null, false, false);
		Movement movement8 = new Movement(1, Strategy.COLOR, movement7, 2, true, true, false, false, false, false, null, false, false);
		Movement movement9 = new Movement(1, Strategy.COLOR, movement8, 3, true, true, false, false, false, false, null, false, false);
		Movement movement10 = new Movement(1, Strategy.COLOR, movement9, 4, true, true, false, false, false, false, null, false, false);
		Movement movement11 = new Movement(1, Strategy.COLOR, movement10, 5, true, true, false, false, false, false, null, false, false);
		Movement movement12 = new Movement(1, Strategy.COLOR, movement11, 6, true, true, false, false, false, false, null, false, false);
		Movement movement13 = new Movement(1, Strategy.COLOR, movement12, 7, true, true, false, false, false, false, null, false, false);
		Movement movement14 = new Movement(1, Strategy.COLOR, movement13, 8, true, true, false, false, false, false, null, false, false);
		Movement movement15 = new Movement(1, Strategy.COLOR, movement14, 9, true, true, false, false, false, false, null, false, false);
		Movement movement16 = new Movement(1, Strategy.COLOR, movement15, 10, true, true, false, false, false, false, null, false, false);
		Movement movement17 = new Movement(2, Strategy.SHAPE, movement16, 0, false, true, false, false, false, false, null, false, false);
		Movement movement18 = new Movement(2, Strategy.SHAPE, movement17, 0, false, false, false, true, false, false, null, false, false);
		Movement movement19 = new Movement(2, Strategy.SHAPE, movement18, 1, true, false, true, false, false, false, null, false, false);
		Movement movement20 = new Movement(2, Strategy.SHAPE, movement19, 2, true, false, true, false, false, false, null, false, false);
		Movement movement21 = new Movement(2, Strategy.SHAPE, movement20, 3, true, false, true, false, false, false, null, false, false);
		Movement movement22 = new Movement(2, Strategy.SHAPE, movement21, 4, true, false, true, false, false, false, null, false, false);
		Movement movement23 = new Movement(2, Strategy.SHAPE, movement22, 5, true, false, true, false, false, false, null, false, false);
		Movement movement24 = new Movement(2, Strategy.SHAPE, movement23, 6, true, false, true, false, false, false, null, false, false);
		Movement movement25 = new Movement(2, Strategy.SHAPE, movement24, 7, true, false, true, false, false, false, null, false, false);
		Movement movement26 = new Movement(2, Strategy.SHAPE, movement25, 8, true, false, true, false, false, false, null, false, false);
		Movement movement27 = new Movement(2, Strategy.SHAPE, movement26, 9, true, false, true, false, false, false, null, false, false);
		Movement movement28 = new Movement(2, Strategy.SHAPE, movement27, 10, true, false, true, false, false, false, null, false, false);
		Movement movement29 = new Movement(3, Strategy.NUMBER, movement28, 0, false, false, true, false, false, false, null, false, false);
		Movement movement30 = new Movement(3, Strategy.NUMBER, movement29, 0, false, true, false, false, false, false, null, false, false);
		Movement movement31 = new Movement(3, Strategy.NUMBER, movement30, 0, false, true, false, false, false, false, null, false, false);
		Movement movement32 = new Movement(3, Strategy.NUMBER, movement31, 0, false, true, false, false, false, false, null, false, false);
		Movement movement33 = new Movement(3, Strategy.NUMBER, movement32, 0, false, true, false, false, false, false, null, false, false);
		Movement movement34 = new Movement(3, Strategy.NUMBER, movement33, 0, false, true, false, false, false, false, null, false, false);
		Movement movement35 = new Movement(3, Strategy.NUMBER, movement34, 0, false, true, false, false, false, false, null, false, false);
		Movement movement36 = new Movement(3, Strategy.NUMBER, movement35, 0, false, true, false, false, false, false, null, false, false);
		Movement movement37 = new Movement(3, Strategy.NUMBER, movement36, 0, false, true, false, false, false, false, null, false, false);
		Movement movement38 = new Movement(3, Strategy.NUMBER, movement37, 0, false, true, false, false, false, false, null, false, false);
		Movement movement39 = new Movement(3, Strategy.NUMBER, movement38, 0, false, true, false, false, false, false, null, false, false);
		Movement movement40 = new Movement(3, Strategy.NUMBER, movement39, 0, false, true, false, false, false, false, null, false, false);
		Movement movement41 = new Movement(3, Strategy.NUMBER, movement40, 0, false, true, false, false, false, false, null, false, false);
		Movement movement42 = new Movement(3, Strategy.NUMBER, movement41, 0, false, true, false, false, false, false, null, false, false);
		Movement movement43 = new Movement(3, Strategy.NUMBER, movement42, 0, false, true, false, false, false, false, null, false, false);
		Movement movement44 = new Movement(3, Strategy.NUMBER, movement43, 0, false, true, false, false, false, false, null, false, false);
		Movement movement45 = new Movement(3, Strategy.NUMBER, movement44, 0, false, true, false, false, false, false, null, false, false);
		Movement movement46 = new Movement(3, Strategy.NUMBER, movement45, 0, false, true, false, false, false, false, null, false, false);
		Movement movement47 = new Movement(3, Strategy.NUMBER, movement46, 0, false, true, false, false, false, false, null, false, false);
		Movement movement48 = new Movement(3, Strategy.NUMBER, movement47, 0, false, true, false, false, false, false, null, false, false);
		Movement movement49 = new Movement(3, Strategy.NUMBER, movement48, 0, false, true, false, false, false, false, null, false, false);
		Movement movement50 = new Movement(3, Strategy.NUMBER, movement49, 0, false, true, false, false, false, false, null, false, false);
		Movement movement51 = new Movement(3, Strategy.NUMBER, movement50, 0, false, true, false, false, false, false, null, false, false);
		Movement movement52 = new Movement(3, Strategy.NUMBER, movement51, 0, false, true, false, false, false, false, null, false, false);
		Movement movement53 = new Movement(3, Strategy.NUMBER, movement52, 0, false, true, false, false, false, false, null, false, false);
		Movement movement54 = new Movement(3, Strategy.NUMBER, movement53, 0, false, true, false, false, false, false, null, false, false);
		Movement movement55 = new Movement(3, Strategy.NUMBER, movement54, 0, false, true, false, false, false, false, null, false, false);
		Movement movement56 = new Movement(3, Strategy.NUMBER, movement55, 0, false, true, false, false, false, false, null, false, false);
		Movement movement57 = new Movement(3, Strategy.NUMBER, movement56, 0, false, true, false, false, false, false, null, false, false);
		Movement movement58 = new Movement(3, Strategy.NUMBER, movement57, 0, false, true, false, false, false, false, null, false, false);
		Movement movement59 = new Movement(3, Strategy.NUMBER, movement58, 0, false, true, false, false, false, false, null, false, false);
		Movement movement60 = new Movement(3, Strategy.NUMBER, movement59, 0, false, true, false, false, false, false, null, false, false);
		Movement movement61 = new Movement(3, Strategy.NUMBER, movement60, 0, false, true, false, false, false, false, null, false, false);
		Movement movement62 = new Movement(3, Strategy.NUMBER, movement61, 0, false, true, false, false, false, false, null, false, false);
		Movement movement63 = new Movement(3, Strategy.NUMBER, movement62, 0, false, true, false, false, false, false, null, false, false);
		Movement movement64 = new Movement(3, Strategy.NUMBER, movement63, 0, false, true, false, false, false, false, null, false, false);
		Movement movement65 = new Movement(1, Strategy.NUMBER, movement64, 0, false, true, false, false, false, false, null, false, false);
		Movement movement66 = new Movement(1, Strategy.NUMBER, movement65, 0, false, true, false, false, false, false, null, false, false);
		Movement movement67 = new Movement(1, Strategy.NUMBER, movement66, 0, false, true, false, false, false, false, null, false, false);
		Movement movement68 = new Movement(1, Strategy.NUMBER, movement67, 0, false, true, false, false, false, false, null, false, false);
		Movement movement69 = new Movement(1, Strategy.NUMBER, movement68, 0, false, true, false, false, false, false, null, false, false);
		Movement movement70 = new Movement(1, Strategy.NUMBER, movement69, 0, false, true, false, false, false, false, null, false, false);
		Movement movement71 = new Movement(1, Strategy.NUMBER, movement70, 0, false, true, false, false, false, false, null, false, false);
		Movement movement72 = new Movement(1, Strategy.NUMBER, movement71, 0, false, true, false, false, false, false, null, false, false);
		Movement movement73 = new Movement(1, Strategy.NUMBER, movement72, 0, false, true, false, false, false, false, null, false, false);
		Movement movement74 = new Movement(1, Strategy.NUMBER, movement73, 0, false, true, false, false, false, false, null, false, false);
		Movement movement75 = new Movement(1, Strategy.NUMBER, movement74, 0, false, true, false, false, false, false, null, false, false);
		Movement movement76 = new Movement(1, Strategy.NUMBER, movement75, 0, false, true, false, false, false, false, null, false, false);
		Movement movement77 = new Movement(1, Strategy.NUMBER, movement76, 0, false, true, false, false, false, false, null, false, false);
		Movement movement78 = new Movement(1, Strategy.NUMBER, movement77, 0, false, true, false, false, false, false, null, false, false);
		Movement movement79 = new Movement(1, Strategy.NUMBER, movement78, 0, false, true, false, false, false, false, null, false, false);
		Movement movement80 = new Movement(1, Strategy.NUMBER, movement79, 0, false, true, false, false, false, false, null, false, false);
		Movement movement81 = new Movement(2, Strategy.NUMBER, movement80, 0, false, true, false, false, false, false, null, false, false);
		Movement movement82 = new Movement(2, Strategy.NUMBER, movement81, 0, false, true, false, false, false, false, null, false, false);
		Movement movement83 = new Movement(2, Strategy.NUMBER, movement82, 0, false, true, false, false, false, false, null, false, false);
		Movement movement84 = new Movement(2, Strategy.NUMBER, movement83, 0, false, true, false, false, false, false, null, false, false);
		Movement movement85 = new Movement(2, Strategy.NUMBER, movement84, 0, false, true, false, false, false, false, null, false, false);
		Movement movement86 = new Movement(2, Strategy.NUMBER, movement85, 0, false, true, false, false, false, false, null, false, false);
		Movement movement87 = new Movement(2, Strategy.NUMBER, movement86, 0, false, true, false, false, false, false, null, false, false);
		Movement movement88 = new Movement(2, Strategy.NUMBER, movement87, 0, false, true, false, false, false, false, null, false, false);
		Movement movement89 = new Movement(2, Strategy.NUMBER, movement88, 0, false, true, false, false, false, false, null, false, false);
		Movement movement90 = new Movement(2, Strategy.NUMBER, movement89, 0, false, true, false, false, false, false, null, false, false);
		Movement movement91 = new Movement(2, Strategy.NUMBER, movement90, 0, false, true, false, false, false, false, null, false, false);
		Movement movement92 = new Movement(2, Strategy.NUMBER, movement91, 0, false, true, false, false, false, false, null, false, false);
		Movement movement93 = new Movement(3, Strategy.NUMBER, movement92, 0, false, true, false, false, false, false, null, false, false);
		Movement movement94 = new Movement(3, Strategy.NUMBER, movement93, 0, false, true, false, false, false, false, null, false, false);
		Movement movement95 = new Movement(3, Strategy.NUMBER, movement94, 0, false, true, false, false, false, false, null, false, false);
		Movement movement96 = new Movement(3, Strategy.NUMBER, movement95, 0, false, true, false, false, false, false, null, false, false);
		Movement movement97 = new Movement(3, Strategy.NUMBER, movement96, 0, false, true, false, false, false, false, null, false, false);
		Movement movement98 = new Movement(3, Strategy.NUMBER, movement97, 0, false, true, false, false, false, false, null, false, false);
		Movement movement99 = new Movement(3, Strategy.NUMBER, movement98, 0, false, true, false, false, false, false, null, false, false);
		Movement movement100 = new Movement(3, Strategy.NUMBER, movement99, 0, false, true, false, false, false, false, null, false, false);
		Movement movement101 = new Movement(3, Strategy.NUMBER, movement100, 0, false, true, false, false, false, false, null, false, false);
		Movement movement102 = new Movement(3, Strategy.NUMBER, movement101, 0, false, true, false, false, false, false, null, false, false);
		Movement movement103 = new Movement(3, Strategy.NUMBER, movement102, 0, false, true, false, false, false, false, null, false, false);
		Movement movement104 = new Movement(3, Strategy.NUMBER, movement103, 0, false, true, false, false, false, false, null, false, false);
		Movement movement105 = new Movement(3, Strategy.NUMBER, movement104, 0, false, true, false, false, false, false, null, false, false);
		Movement movement106 = new Movement(3, Strategy.NUMBER, movement105, 0, false, true, false, false, false, false, null, false, false);
		Movement movement107 = new Movement(3, Strategy.NUMBER, movement106, 0, false, true, false, false, false, false, null, false, false);
		Movement movement108 = new Movement(3, Strategy.NUMBER, movement107, 0, false, true, false, false, false, false, null, false, false);
		Movement movement109 = new Movement(3, Strategy.NUMBER, movement108, 0, false, true, false, false, false, false, null, false, false);
		Movement movement110 = new Movement(3, Strategy.NUMBER, movement109, 0, false, true, false, false, false, false, null, false, false);
		Movement movement111 = new Movement(3, Strategy.NUMBER, movement110, 0, false, true, false, false, false, false, null, false, false);
		Movement movement112 = new Movement(3, Strategy.NUMBER, movement111, 0, false, true, false, false, false, false, null, false, false);
		Movement movement113 = new Movement(3, Strategy.NUMBER, movement112, 0, false, true, false, false, false, false, null, false, false);
		Movement movement114 = new Movement(3, Strategy.NUMBER, movement113, 0, false, true, false, false, false, false, null, false, false);
		Movement movement115 = new Movement(3, Strategy.NUMBER, movement114, 0, false, true, false, false, false, false, null, false, false);
		Movement movement116 = new Movement(3, Strategy.NUMBER, movement115, 0, false, true, false, false, false, false, null, false, false);
		Movement movement117 = new Movement(3, Strategy.NUMBER, movement116, 0, false, true, false, false, false, false, null, false, false);
		Movement movement118 = new Movement(3, Strategy.NUMBER, movement117, 0, false, true, false, false, false, false, null, false, false);
		Movement movement119 = new Movement(3, Strategy.NUMBER, movement118, 0, false, true, false, false, false, false, null, false, false);
		Movement movement120 = new Movement(3, Strategy.NUMBER, movement119, 0, false, true, false, false, false, false, null, false, false);
		Movement movement121 = new Movement(3, Strategy.NUMBER, movement120, 0, false, true, false, false, false, false, null, false, false);
		Movement movement122 = new Movement(3, Strategy.NUMBER, movement121, 0, false, true, false, false, false, false, null, false, false);
		Movement movement123 = new Movement(3, Strategy.NUMBER, movement122, 0, false, true, false, false, false, false, null, false, false);
		Movement movement124 = new Movement(3, Strategy.NUMBER, movement123, 0, false, true, false, false, false, false, null, false, false);
		Movement movement125 = new Movement(3, Strategy.NUMBER, movement124, 0, false, true, false, false, false, false, null, false, false);
		Movement movement126 = new Movement(3, Strategy.NUMBER, movement125, 0, false, true, false, false, false, false, null, false, false);
		Movement movement127 = new Movement(3, Strategy.NUMBER, movement126, 0, false, true, false, false, false, false, null, false, false);
		Movement movement128 = new Movement(3, Strategy.NUMBER, movement127, 0, false, true, false, false, false, false, null, false, false);
		Manager.getInstance().getMovements().add(movement1);
		Manager.getInstance().getMovements().add(movement2);
		Manager.getInstance().getMovements().add(movement3);
		Manager.getInstance().getMovements().add(movement4);
		Manager.getInstance().getMovements().add(movement5);
		Manager.getInstance().getMovements().add(movement6);
		Manager.getInstance().getMovements().add(movement7);
		Manager.getInstance().getMovements().add(movement8);
		Manager.getInstance().getMovements().add(movement9);
		Manager.getInstance().getMovements().add(movement10);
		Manager.getInstance().getMovements().add(movement11);
		Manager.getInstance().getMovements().add(movement12);
		Manager.getInstance().getMovements().add(movement13);
		Manager.getInstance().getMovements().add(movement14);
		Manager.getInstance().getMovements().add(movement15);
		Manager.getInstance().getMovements().add(movement16);
		Manager.getInstance().getMovements().add(movement17);
		Manager.getInstance().getMovements().add(movement18);
		Manager.getInstance().getMovements().add(movement19);
		Manager.getInstance().getMovements().add(movement20);
		Manager.getInstance().getMovements().add(movement21);
		Manager.getInstance().getMovements().add(movement22);
		Manager.getInstance().getMovements().add(movement23);
		Manager.getInstance().getMovements().add(movement24);
		Manager.getInstance().getMovements().add(movement25);
		Manager.getInstance().getMovements().add(movement26);
		Manager.getInstance().getMovements().add(movement27);
		Manager.getInstance().getMovements().add(movement28);
		Manager.getInstance().getMovements().add(movement29);
		Manager.getInstance().getMovements().add(movement30);
		Manager.getInstance().getMovements().add(movement31);
		Manager.getInstance().getMovements().add(movement32);
		Manager.getInstance().getMovements().add(movement33);
		Manager.getInstance().getMovements().add(movement34);
		Manager.getInstance().getMovements().add(movement35);
		Manager.getInstance().getMovements().add(movement36);
		Manager.getInstance().getMovements().add(movement37);
		Manager.getInstance().getMovements().add(movement38);
		Manager.getInstance().getMovements().add(movement39);
		Manager.getInstance().getMovements().add(movement40);
		Manager.getInstance().getMovements().add(movement41);
		Manager.getInstance().getMovements().add(movement42);
		Manager.getInstance().getMovements().add(movement43);
		Manager.getInstance().getMovements().add(movement44);
		Manager.getInstance().getMovements().add(movement45);
		Manager.getInstance().getMovements().add(movement46);
		Manager.getInstance().getMovements().add(movement47);
		Manager.getInstance().getMovements().add(movement48);
		Manager.getInstance().getMovements().add(movement49);
		Manager.getInstance().getMovements().add(movement50);
		Manager.getInstance().getMovements().add(movement51);
		Manager.getInstance().getMovements().add(movement52);
		Manager.getInstance().getMovements().add(movement53);
		Manager.getInstance().getMovements().add(movement54);
		Manager.getInstance().getMovements().add(movement55);
		Manager.getInstance().getMovements().add(movement56);
		Manager.getInstance().getMovements().add(movement57);
		Manager.getInstance().getMovements().add(movement58);
		Manager.getInstance().getMovements().add(movement59);
		Manager.getInstance().getMovements().add(movement60);
		Manager.getInstance().getMovements().add(movement61);
		Manager.getInstance().getMovements().add(movement62);
		Manager.getInstance().getMovements().add(movement63);
		Manager.getInstance().getMovements().add(movement64);
		Manager.getInstance().getMovements().add(movement65);
		Manager.getInstance().getMovements().add(movement66);
		Manager.getInstance().getMovements().add(movement67);
		Manager.getInstance().getMovements().add(movement68);
		Manager.getInstance().getMovements().add(movement69);
		Manager.getInstance().getMovements().add(movement70);
		Manager.getInstance().getMovements().add(movement71);
		Manager.getInstance().getMovements().add(movement72);
		Manager.getInstance().getMovements().add(movement73);
		Manager.getInstance().getMovements().add(movement74);
		Manager.getInstance().getMovements().add(movement75);
		Manager.getInstance().getMovements().add(movement76);
		Manager.getInstance().getMovements().add(movement77);
		Manager.getInstance().getMovements().add(movement78);
		Manager.getInstance().getMovements().add(movement79);
		Manager.getInstance().getMovements().add(movement80);
		Manager.getInstance().getMovements().add(movement81);
		Manager.getInstance().getMovements().add(movement82);
		Manager.getInstance().getMovements().add(movement83);
		Manager.getInstance().getMovements().add(movement84);
		Manager.getInstance().getMovements().add(movement85);
		Manager.getInstance().getMovements().add(movement86);
		Manager.getInstance().getMovements().add(movement87);
		Manager.getInstance().getMovements().add(movement88);
		Manager.getInstance().getMovements().add(movement89);
		Manager.getInstance().getMovements().add(movement90);
		Manager.getInstance().getMovements().add(movement91);
		Manager.getInstance().getMovements().add(movement92);
		Manager.getInstance().getMovements().add(movement93);
		Manager.getInstance().getMovements().add(movement94);
		Manager.getInstance().getMovements().add(movement95);
		Manager.getInstance().getMovements().add(movement96);
		Manager.getInstance().getMovements().add(movement97);
		Manager.getInstance().getMovements().add(movement98);
		Manager.getInstance().getMovements().add(movement99);
		Manager.getInstance().getMovements().add(movement100);
		Manager.getInstance().getMovements().add(movement101);
		Manager.getInstance().getMovements().add(movement102);
		Manager.getInstance().getMovements().add(movement103);
		Manager.getInstance().getMovements().add(movement104);
		Manager.getInstance().getMovements().add(movement105);
		Manager.getInstance().getMovements().add(movement106);
		Manager.getInstance().getMovements().add(movement107);
		Manager.getInstance().getMovements().add(movement108);
		Manager.getInstance().getMovements().add(movement109);
		Manager.getInstance().getMovements().add(movement110);
		Manager.getInstance().getMovements().add(movement111);
		Manager.getInstance().getMovements().add(movement112);
		Manager.getInstance().getMovements().add(movement113);
		Manager.getInstance().getMovements().add(movement114);
		Manager.getInstance().getMovements().add(movement115);
		Manager.getInstance().getMovements().add(movement116);
		Manager.getInstance().getMovements().add(movement117);
		Manager.getInstance().getMovements().add(movement118);
		Manager.getInstance().getMovements().add(movement119);
		Manager.getInstance().getMovements().add(movement120);
		Manager.getInstance().getMovements().add(movement121);
		Manager.getInstance().getMovements().add(movement122);
		Manager.getInstance().getMovements().add(movement123);
		Manager.getInstance().getMovements().add(movement124);
		Manager.getInstance().getMovements().add(movement125);
		Manager.getInstance().getMovements().add(movement126);
		Manager.getInstance().getMovements().add(movement127);
		Manager.getInstance().getMovements().add(movement128);
		Manager.getInstance().setCategorySequenceNumber(3);
		
		//Finishing test
		Manager.getInstance().setFinalTime(Calendar.getInstance());
		String fileName = Constants.PDF_FILE_NAME_PREFIX + " - " + Manager.getInstance().getUserName() + ".pdf";
        String filePath = Constants.PDF_FILE_PATH + fileName;
        PDFGenerator mPDFGenerator = new PDFGenerator(filePath);
        mPDFGenerator.generateAndShowPDFFile();
		System.exit(0);
	}
}